name: FEX 百度 Web 前端研发部
url: http://fex.baidu.com
source:      .
destination: ./_site
plugins:     ./_plugins
lsi:      false
safe:     false
markdown: redcarpet
#pygments: true
#permalink: pretty
permalink: /blog/:year/:month/:title
paginate: 12
paginate_path: "articles/page:num"
encoding: utf-8

post_defaults:
  layout: post

redcarpet:
  extensions: ["tables", "autolink"]
